[tool.poetry]
name = "dicquo"
version = "3.0.0"
description = "Веб-приложение для коллекции цитат и афоризмов."
authors = ["Sergei Erjemin <erjemin@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^6.0.2"
django-taggit = "^6.1.0"
pillow = "^12.1.1"
pytils = "^0.4.4"
etpgrf = "^0.1.4"
django-environ = "^0.12.1"
whitenoise = "^6.11.0"
gunicorn = "^25.1.0"
tqdm = "^4.67.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
