# Generated by Django 6.0.2 on 2026-02-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_tbdictumandquotes_bischecked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbdictumandquotes',
            name='bTypograph',
            field=models.BooleanField(db_index=True, default=True, help_text='Применять типографику?', verbose_name='Типографировать'),
        ),
        migrations.AlterField(
            model_name='tbdictumandquotes',
            name='szContent',
            field=models.TextField(default='', help_text='Не обязательно.', max_length=640, verbose_name='Изречение'),
        ),
        migrations.AlterField(
            model_name='tbdictumandquotes',
            name='szContentHTML',
            field=models.TextField(blank=True, default='', help_text='Содержание цитаты, афоризма, высказывания…<br /> Свёрстано в HTML по правилам типографики', verbose_name='Изречение HTML'),
        ),
        migrations.AlterField(
            model_name='tbdictumandquotes',
            name='szIntroHTML',
            field=models.TextField(blank=True, default='', help_text='Автор и, если необходимо, краткая справка<br /> Вступление перед цитатой, в HTML по правилам типографики</small>', verbose_name='Вступление HTML'),
        ),
    ]
