# Generated by Django 6.0.2 on 2026-03-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_tbdictumandquotes_btypograph_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbdictumandquotes',
            options={'ordering': ['-id'], 'verbose_name': 'ВЫСКАЗЫВАНИЕ', 'verbose_name_plural': 'ВЫСКАЗЫВАНИЯ'},
        ),
    ]
